apiVersion: v1
kind: Service
metadata:
  name: app1-svc
spec:
  # On docker desktop load-balancer type would map service to 'localhost'
  type: LoadBalancer
  selector:
    app: app1
  ports:
  - port: 80
    targetPort: 3000
